### PR TITLE
support HEAD requests

### PR DESCRIPTION
**Pull request by jpillora**

### CODE REVIEW

**Comment by jpillora** [comment]
I assumed this would work, though I'm getting 400 Bad Request in my testing, will report back 👍

**Comment by jpillora** [comment]
False alarm, was missing credentials, working

**Review by mdwhatcott — CHANGES_REQUESTED** [review]

**Comment by jpillora** [comment]
Sorry this PR should have been in a branch, Will do

**Comment by jpillora** [comment]
See #7

**Pull request closed without merging**
